local assert = require("luassert.assert")
local stub = require("luassert.stub")
local commenter = require("bulk-comment.commenter")

describe("testing init", function ()
  before_each(function ()
   stub_nvim_echo = stub(vim.api, "nvim_echo") 
  end)
  local plugin = require("bulk-comment")
  it("calling toggle", function ()
    plugin.toggle()
    assert.stub(stub_nvim_echo).was_called_with({ { "Not yet supported" } }, true, { err = false })
  end)
  it("calling block_toggle", function ()
    plugin.block_toggle()
    assert.stub(stub_nvim_echo).was_called_with({ { "Not yet supported" } }, true, { err = false })
  end)
end)
